// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByPe2DFzNOihhdFJJsWt0shrsY30FozKQ',
    appId: '1:315416943230:web:8c8b05d06b1450be33d62f',
    messagingSenderId: '315416943230',
    projectId: 'okok-coffee-faa2a',
    authDomain: 'okok-coffee-faa2a.firebaseapp.com',
    storageBucket: 'okok-coffee-faa2a.appspot.com',
    measurementId: 'G-VZTTTS8GWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnUwcosdlG3EInudcsrfAYCraWKN6ueEw',
    appId: '1:315416943230:android:95b09411e966ef4e33d62f',
    messagingSenderId: '315416943230',
    projectId: 'okok-coffee-faa2a',
    storageBucket: 'okok-coffee-faa2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGRgi64RyWNxQ6EDnZ1dio-g7N1oco_-Y',
    appId: '1:315416943230:ios:e2fa04d984e00e4e33d62f',
    messagingSenderId: '315416943230',
    projectId: 'okok-coffee-faa2a',
    storageBucket: 'okok-coffee-faa2a.appspot.com',
    iosBundleId: 'com.example.okokCoffe',
  );
}
